project:
  title: "qgreenland-2023-researcher-workshop"
  type: "website"
  render:
    - "*.qmd"
    - "*.md"
    - "!doc/"


website:
  title: "QGreenland Researcher Workshop 2023"
  # description: TODO
  site-url: "https://nsidc.github.io/qgreenland-2023-researcher-workshop"

  repo-url: &repo-url "https://github.com/nsidc/qgreenland-2023-researcher-workshop"
  repo-subdir: "content"
  repo-actions: ["edit", "issue"]

  navbar:
    left:
      - text: "Course content"
        file: "content/index.qmd"
      - text: "Prerequisites"
        file: "content/prerequisites/index.qmd"
    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url

  sidebar:
    - title: "Prerequisites"
      contents:
        - "content/prerequisites/index.qmd"
        - "content/prerequisites/dataset_selection.md"
        - "content/prerequisites/assessment.md"

    # HACK: Without this line, the sidebar above shows up on every page.
    # https://github.com/quarto-dev/quarto-cli/issues/1853
    - title: "Placeholder"


  page-footer:
    left: "Built with [Quarto](https://quarto.org/) ❤️"
    right:
      - text: "Code of Conduct"
        href: "CODE_OF_CONDUCT.md"
      - text: "License"
        href: "LICENSE.md"


format:
  html:
    theme: "cosmo"
    # TODO: Support light/dark switch?
    # theme:
    #   light: [cosmo]
    #   dark: [cosmo, dark.css]
    css: "content/custom.css"
    toc: true
