name: qgreenland-researcher-workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10

  - quarto ~=1.3.340
  - jupyter ~=1.0.0
  - xarray ~=2023.03
  - rioxarray ~=0.14.1
  - matplotlib-base ~=3.7.1
