project:
  title: "qgreenland-2023-researcher-workshop-slides"
  type: "website"

website:
  title: "QGreenland Researcher Workshop 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: "cosmo"
    css: "custom.css"
    toc: true
