project:
  title: "qgreenland-2023-researcher-workshop-slides"
  type: "website"
  output-dir: "_dist"

format:
  revealjs:
    toc: true
    toc-depth: 2
    overview: true
    theme: "dark"
    slide-number: true
    chalkboard:
      buttons: true
    preview-links: "auto"
    logo: "https://nsidc.org/themes/custom/nsidc/logo.svg" 
    footer: "<https://nsidc.org>"
    strip-comments: true
    transition: "convex"

    # Themes:
    #   beige
    #   blood
    #   dark
    #   default
    #   league
    #   moon
    #   night
    #   serif
    #   simple
    #   sky
    #   solarized
